apiVersion: v1
kind: Secret
metadata:
  name: config-repository-credentials
  namespace: "argocd"
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: "https://github.com/MaikBuse/cloud-config.git"
  type: helm
  githubAppID: <github-app-id>
  githubAppInstallationID: <github-app-installation-id>
  githubAppPrivateKey: |
    "- xy"
