apiVersion: v1
kind: Secret
metadata:
  name: "cloud-config"
  namespace: "argocd"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "https://github.com/MaikBuse/cloud-config.git"
