apiVersion: v1
kind: Secret
metadata:
  name: "vectory-backend-keycloak-secret"
  namespace: "vectory"
type: Opaque
stringData:
  KEYCLOAK_URL: <keycloak-url>
  KEYCLOAK_ID: <keycloak-id-of-user>
  KEYCLOAK_USERNAME: <keycloak-username>
  KEYCLOAK_PASSWORD: <keycloak-password>
  KEYCLOAK_REALM: <keycloak-realm>
  KEYCLOAK_CLIENT: <keycloak-id-of-client>
  KEYCLOAK_SECRET: <keycloak-client-secret>
