apiVersion: v1
kind: Secret
metadata:
  name: "pgo-s3-creds-secret"
  namespace: "vectory"
type: Opaque
stringData:
  s3.conf: |
    [global]
    repo1-s3-key=<YOUR_AWS_S3_KEY>
    repo1-s3-key-secret=<YOUR_AWS_S3_KEY_SECRET>
