apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: vectory
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.2-0
  postgresVersion: 16
  instances:
    - name: vectory
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  users:
    - name: "vectory"
      options: 'SUPERUSER'
      databases:
        - vectory
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.49-0
      configuration:
      - secret:
          name: pgo-s3-creds-secret
      global:
        repo1-path: /vectory
        repo1-retention-full: "3"
        repo1-retention-full-type: count
      manual:
        repoName: repo1
        options:
         - --type=full
      repos:
      - name: repo1
        s3:
          bucket: "kube-hetzner-postgres-backups"
          endpoint: "s3.amazonaws.com"
          region: "eu-central-1"
        schedules:
          full: "0 0 * * 1"
          differential: "0 1-23 * * *"
