apiVersion: v1
kind: Service
metadata:
  name: "vectory-backend-service"
  namespace: "vectory"
  labels:
    app: "vectory-backend-service"
spec:
  selector:
    app: "vectory-backend"
  ports:
    - name: "go"
      protocol: TCP
      port: 3000
      targetPort: "go"
