apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "backend-ingress"
  namespace: "vectory"
  annotations:
    cert-manager.io/cluster-issuer: "common-prod-cluster-issuer"
spec:
  tls:
    - hosts:
        - api.vectory.dev
      secretName: backend-ingress-secret
  rules:
    - host: api.vectory.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "vectory-backend-service"
                port:
                  name: "go"
