---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-secret
  namespace: home
spec:
  encryptedData:
    .dockerconfigjson: AgBncC3QKm2qiPDN0vOyasQOkfVuX2jJIqPrZN2n8gP+RaZ8VW57l71y46+Mn2HUQRC2AhLOGw/3bY0eptf+1ZLloc0NkUbbEwjkNQE9HZj+l6Ctkc0wLqmesCyLIz+Bv/AHMuXjm01dfsW5eM0sctvek5DifwR2u4HuUZJtmvRuR3ac0JsF2kMFQGOphwWegV2wy7Y6QrwffdGZFj1jdyTb+7d2BTm3hxkNZ9o8WoIrGZYseU35g+PcAPqY2c5Cnc1ItvG2xAN8mjpDeR+k91rFQPJAsOyKgj4+KfQbouDCwjzbt/ykexwhSQyBVnDg+kmwdmG6AO7Y4cFr5qgXqJAioEOKp8QlHrH+HWY7depY5v8dbP45y8j5LTdbBZA8pVt+M4G47KptE8j4SqX21K68v9KdxwyhjZ1InSXKTSn/FKRIezaNTSnkdi0JgAc7c4I1XaIrxVrxg+O5TLOKBCfd7Mg3ztO8+xBdH1Y3MthTvYqzEGWNxRTz7lovgaMokszRAcPPaHGRhUqqHVQCiNmX/2GrEvfqKkD2oEkcMMLyRrzpAXYN9kxJkFadIvO1u/+C0RqfC7orMVoa5WVQwpCJSEzhVBmDoWZNpKm7QvvcnUmoTVzBGF/nj606SatigPmwdbB9hxAE+vflVYK5/AQhoKSWQzDrAojAbyXsvWYDmsfJW1usH8jxZLVkTfTY3a3LL2iHEzX6+de8dhvWPSo2NKhVRSMum1HWYDg3xbOaClvuX0AAqA57NRUhI3/EHZ6RGkiqBOiXjxltpe2oBid9QECcuriLY8xvpsXCksJLbI6oDXZkmNCq2x38Gb3gVOcD8P0EcQ6PYvTk6/V5AjR2gpWgCabt0i8sWGOwNwqV8WjDPs2teh/1VFI7grlWcQKLMoGvRsSJ89D6uTcUMO2ImyDU5zBS0SvnIVQj4Me+tpc3NJqE6dCrXxQfsUL8SMkTPDfLT439JJOVZA+jx7Q82X01PVc+
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-secret
      namespace: home
    type: kubernetes.io/dockerconfigjson
