---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-pull-secret
  namespace: home
spec:
  encryptedData:
    .dockerconfigjson: AgAehn4QSZnvGb6/w9rdK9yYQ/Dvb2/eYoZ/igq1HowP24vcwCn5ZU91MKBMYiCDcgkYGwgjkTmYBTBAUTiJobPm1Z2I/P1Qc3EgBYoRVlK7V8df1vIWVUNH9bNczKtTnqVv9X+HU2p2F2uVeyl/TqCtL5CfMZ4PNcZcYH+PSemkzFYnwaqVztmMb/auZJ+86lPq8cEj1TpnY3Y0cd2AlQRkxo0Zc8rJlAbzstE6o3ZEO1cxUIpCQ5yHu2/eXhXTMtCWAHjm2VeWPNbdZMh5FIlfww3RLnZg5QFfvjlHFT/fSAxNCYY6MLkq0KE0alYPEl7vCfLuRFGMCs2JfN5IYewvWUFngpSF+HvFJI8s0LdackgZ17zb8ukqc3au5uYdH7To8xltpho2WNKdf2sGk4kdC3m3YHI/zgwTXnQDRKrpsPMuvds83NGOH+62Da55A/IG/zym4BiUwHzYC+cDCTyIN/3vFzxT3xhyZtkmzOyMfJRWfagbIrqxP1GANJJWy1PzMXLIYcc/V2Hf5tP8BZP+LoUO4myqGwBkwoJpLhrqKqcIprlKVGSRS3SNYVa6TpOrLR7MtWbpUz5305WzuecNQe53Pf5YqcVHPxL74R1r9tcsJxMXSTtoagL4w1T6uJqgQ7OIo+cS7EP06v56aN0/cKoyaFtVpngbf+msORvtjdSaQYljvhCTSUdH0rdbREBoOkFp7SiWFl24ZxyvrTMtAtOIOf6bHPGJO00UV7ck1rdX9kzNK7RJ0kC09qkNp6D5NLP5KC0xr3eCySt/6VxywEXb8lT9KB2RxKVHI3RHxlEx88Zxixql2Z1V1efewpE0gUO8zN8nMSG4c2ltUm5oWm+POJRmeOMxbR0ize5quh20xwb7U7s+yE6Cn3NjZJ2X0xX47WW7DENbKlat4nt0lkIxUJ1kaKw6y5d9mQURmh+7YGw0p/ZnUgzL+z+Y9sNdSIbLeah7YGvdLLahDFMP3w3dv3em
  template:
    metadata:
      creationTimestamp: null
      name: image-pull-secret
      namespace: home
    type: kubernetes.io/dockerconfigjson
