---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBTd1V5cC4jPZjDbcGbCU4kgsApWqxFbgxJJ616srG1gV0/HIaAZSMZHEGeb1VYD5mXCcl5dyaWp6Tt0wS/7L5HIBGDlR8JWDQApHGqE6DMPXbkVhkiGNiYL4+EhvNUmP+Hu4ZVpl+osdc+g//eJ3OFeY4y+6P1kPio+R2agwaYKWjfCz0SSpx2Dp+Uw6P1juMu+iKaRRAUK5QZfj1NO3ZaXcWD/YYlM9PPW749OCZ6kD03jEKvdcgxRqVOKx+clhflQ367J7UseSHU2qmzux8w1B554Y7MZH92RoICRG6lN82y6wIz+Yhy7stTz6Qp5euj4b2uJKQoHA1MjHb3TdMgtc7JpCvrMqjCmwmy0yXxj4g2sZNs///iZCo7rfurzVKLZXs1X4yrwSe/O+jLdnky9pKcMerF//ANOYkgXlMzVx6M3YQpfXr1RRsMBeA4Of2IOqXKuoAvmDtobJNg45uLV+j3qi4q+d2mial3gF38/4eVwsaMSOukq78y4bPRGSr2JKDImkYDoKT3SGa76I/uUeh164u0OwjgXRXUuGeX0mvPt/wWAJUxRy5jGo75XRjtCyDJM9OJyW9O6SUrHF+cDZwc4zzKVjFS+3/GAI5vnqwjPLAysLGHv+phb0S0/GlPMNqWncCHCWq/geKgiQSfbRoStMIqHKcw9xl7LrU5iK3aCd7shOMBn/sRm3qZMQ8xx0JDVtU3Tgmevx+T+ydNT5Z8ueUFxqxDqQlTb3/QnEOanwbLt9WdLWuiYRn1dO6CSos3HAcyh2ntvS5TFOaY
    postgres-password: AgA3BsBZ8Ib9qPavHHF/sy3Tax81T8PcuFdrIZs6EgpvG033skjhUabGqbTTXwSMZA8xpCvRuCnIJcqubS0A+4Lcz1s3yIFC2UOBkg0QlLuBiAzyQ8SNo8jyGDfFRecQV0V75rJr6OXdOa5m06xSBjJYW1jNXSuSUgtSPOQrEfpBQVHSuLPzXZwPF7I9ZVwm15fUtHUjQ+KRYfKUtZ/aWYKXenFw0NbyM/GtnK7308PFMabSTgoI+e46YOmBIExp64TOh7dwnRR/4bCBM17FSZdJpa3tLDVKZMiMW62qPa97xKTxxK2fKaxZttEvnW5YS5GkSlQkHZXOtWhUtv5cyDKdlFVFOFEj1rD81OqPjGbq+TVZuv1RQWI8Bvfixs2eeruuvCJql+lFiIxc5I9LcfTN2jJy1zZL6/hTdQEC6laGj/Ksc5G0EfLLE+GotEOJTRJDNR6vLCbmVninJ50aCiNZ0PaXJ7LGc0ord1o9FAq4kJLC/xOVhJxpykdQNCp+9UurDeop97wWTn4TTPtw6/shursblmGJ7OaxDwcPznOOyLkukEAb/Ap6KSaggur1qh9lmgi+t+LfL5n9SQM2vKEmAbCpNgrQdyEnb8LnYA9eoQg2Y5MiDPGetWU+9DHP5mJfRpfnCJp0OrKkWwrLpxuB0iBf7ThsmxCt7fmRHFPb8WYM9bdeAQZLeN0S3Uk3xcmfUdz1eikbO1y2Cu3hZqE7m8Ug+TzLYfYRgO/7ylPcyNlSOEQebSDsMeUbHyE58+AjZbuxf6ZfoxRrjohmLdzh
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: keycloak
    type: Opaque
