---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgALe/skTs8hetothHH7Bq8hkBgz3ZNntJS7VIRJWJFsGGKU+iO2348l8xgKYp0EFt/axbFxjuGh7zeq4nDos1C++2MkyE9cm18lKFARYgaQ+bgOXmnPLk1qdDBwGCLDjU726d3RX6k7l/Yf0VItE+FdFutgxkKVd+FbTMK6+v/oZT/Uth/NybHOs6Gu94t19M7KWREMSSHZ4yuiaS5EpS2QQiAXLXH+wzvN5tvw1ncbVb+d+rWYa0AaXeCx0dvA5lQAmaI0Cdu/CFsfNCJqyRz3bS5v+YX6Jpxfgdocfl00CI0y2m8tPI0o0qCW8GH1EeA+mMhj9Eaq/FjLEVb0AI5PaJWFe68OAvjqoRMwObb4MvJ/l1QLIk4+1a+SxSzG3REZXSD4CC30wo+4y4OUccUqETePgnEgtjlYaPEPbsThZ5YLCfjATbXOGOvj+iXT0yPKYvOf0W0jwImhNcuH1F7ZPnCjwnjGLLqj0iKaIZBrCYAoTMPZlpC3Psc0vTYGjGETKJnyfc0vLRJEILR/NstYV5/dhPuq83w5zToK9Qj/cFNnoaPN5d9OOz5huyK/0WXj7YG5Eo0LZuhqSYWPnZCJs3kvuvRo6E03I7Or9GKn6iwLJFj8g4d+4R/YRJtK3CcGKbEexBWE3zZUa2Htdvr5/L3yHSCRXFkkmAmydh6Drvzjw/a38W0sBvjgyGDgtqYg1ORRkUac7zYfLSQ=
    client_secret: AgBNcAPtKzv6yFqdzDJNVtXxTvKKVj94eoX+Nc6HSdsdyf7KhkYj6W4mrLaOUfbdeDf3245W/sTEi62vewCnktv3rHMuhItYSTmdOfhS19bpWLJZUMXCG4TMRqPqFH+T6fYk6L3FpK8FpeCdU8f14swaHPeHQHDjuG0Fzzi/oK3esIV96Hi8hZiWwPxPBUAdO5NjHztkngILFu4t5SKfhkDVPNF+I8J645TOuiE5XrKl7MwDXP5O1fj0gNl3xkwFsIpfRzPSoL6TOpfzktlsHGXzZ7GAP6qR2WCa4JctAzLlnl9bE3Ul1VN1x585YHGzPOyTBwKWPUbaB2w4YQUZQAeFrULC+E1QdQs+dq1CteadZxo6C7icGG2IKZsYeV7z4UadDKmsdzL2CXniB6QA3y8MOJ1I0PdFFuIF3ow0BasE7smfsTm2qz9iveoMB1HTJExz/JiYmpPwBB6jl20YEiFM6Hgbn9Go0p+O/ioVDNg1qYD9+SD/e9EdcORD0hCKVKQA2U8OkMgW6y4qWMqBmcEFvUeP0by1sJ4oS9y/YXW9MQQ3SQHVOqL/K2WM2GD/N+M9I0csZgS9Th6iK8G3G74r724SEjbWqYfwJ1Uk0RvZHyu2/o1+m/EEvXULPIZGyab6NkQ7lE3iX4XbAFzURUEUTaZQpTGBkMCAO7MaW+P8xzYvdbRtVRtzeP5KA4jgUUofw4UYboN02sXR8OCphcRkKGQEcyyWAQb9bLgj1nZGNFu30C6p56UOP/8GMPUFVinRUZPtTq5JWVovgw==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
