---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBK7VVgRkXAxJqCk7lhmy8z7yq6vJ95l9dFQaoPg+bXIy06/tsewkiXnOjDto6VQCJESmq0wdMkpjorjZw5G4kLohhx/lW9ZjQC02fOngEW1ysSNhgXSZVxuFIQMOhINeYPGgZ6Veygh7KQTH0TWQjdOmYZnDO0xwq/X+Yn0BkMqTpcerLQBoW//8QzXXKIbTsH4IO5RRcHRnE+dSm3gAHDqeQajFfgrFT2OXC5j9seDJWubRsbavd0XFL/aCJohQ0EOzW1CrUx5qEo5ec934Oui4Xb/kyu+G4M+iV0NhPh7ICO4KRtfLQxl0ereVwYH3Au29UGYULvXEgk+oRgugvN2uJO79S5W0NRKb72ZEXCRfudRs9qIsWgzxzM9B32cTWDeeVPUIZ9PjTLTGWbTjzzVs4kF8RM17yV3QqY9LByR3lWBHCKJZjlDFgSZeMx5rH/8BIXsTX1POrdPSZ0a5rNZqTUd+yDIP1KH0AZ6MyYEjOCRuXzHsR9xqueC7IOnSMWx+FrtGN6T3rYkm5UG1EWhf3nCt+x41rTLwtskuyJMsa9YM3LFe63r+utq/cWhsMk05TAn9LoO5ZIVO/suPbe/tN6fP2clW3Y0trs1+tX4TNlR4T2pzwZuo7QBvwM5cebQDWsdz07SyPluBu2GnsRU8HBI7+nlWYpv16MuKwe5/CKSUMJNWbhnWmrP+2pBr+AGA+Zcn99j/O4hXg=
    client_secret: AgAbFoTu7bT44AfjTp5idwwN0zTLp9I2A8Sf/EfDYiUmcYZEHHyvG+XcbicNINsVk13CBuhUPDS5Ni0CxrieWcW6V28nreqUQVc4IUFVKanaCBOM6d2dfz1eRDD1WrgrkbCn/r0ppQXQxTKd4gl3dcW/UbvBkJTpqKJw+lKkLuugPYlgoH8rB0SyP1ZNwc1C+/j3T9TDb9TtBtpFfXEr0bHOuYwZtiqajql1+BVBTu3u52hUXOstI/cMp1hOqSAcmw/+qzHTUb6rE/u/xac+mFLBzjF68ylPtGPPecehak64QCUbceQzkbMpvShZDoDd4B8ZrwEQ3Jyyj4IGbMFX61kZyIeu+CpyDp+1O0vfgJERbSawrOrkEuVVUldEk/lGQyYYO/vScxGNE5zZMMTyU2Gj8TD/bHz/DndWfU85TnCzHA3oA3Pj/j9xyKuaoLm4XmlFi0W02lI4of3gRrmDeLXvx3q6pAS79QMGziiSU/VCcqFNemkUPLiE8GjcOJipE3oV5kavzNRJRrko7NovrpHbKIUOtdcUUew4F4E1wSkYAUQJ1Y1ddDN0scwNA08RQdgXQJplj2oD/F9/31YTdZwbLQGs/PDDMhdaJjDyv/ac5MicRzToSRpq5USHJZ68r4pWSCuaikrpg5toFf1GcV/gMXllgLEctohC3ce+wprtHdVd4WvDmkZfqGXmnOFl26Sb2KGbrYCo3O6/wK3SCo1ggGu5q8Cms4qX+WShMAMZBOq+0O1ogv8dPqYA2VOvxtbINORB7hAZmijbgg==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
