---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBprZypi2iTs+IHusNAg/1B5m6t5I4htENnsbxEMAzAnUQ5AkUkQ4abnrQYVe66yaM6VpOqQ8fiPg++K1T2+8G1vG+iG4BQEInUMV4kfDDAoJTzLVUBdHEZjgyKp7QPdq+GWRhnGwi3EJscsE55RRbvsgGbptyjKKiXrz8yqfAGaeV1tdyDd2sIflCETJRlJLq9J7PKrIhfxlE8JPDWIKl8+uQ0FTx2IjJy1EO4oh4D4hReHHHtvHYFxszsHHXlQNezk0lu9jCDzyLHHGWYAlS3+vR42RjfMyVErVcHZUA1sLNGpI8YHtm7pvJCYZq8WHnpjPrCysdxYn3zHNZSYdfCCVnqjdR+8rictzsXpt+1IHB+JELY7xgzK7j7kU2vvB8ivh3+Gs93PVOU0KZ/wfXL/1YZ7jB8Snq9slw/HLpiQOrpLpoU/SAt4Z4uhyeK+tu6pzeSQY5uMIR7CP0ZC8uY2Js2MLWKzrArdGxnw9RFv1VG2zbADIYWrfTZmQbRUG19/2pC+bX3k6kfR9ycmSpoDK6N/rCW/i2IEsQ86V0J9iu4x2Qs2lo4Asc7bTmIhvXf8M/cSuhBXm6GhXYczVdv9EYESVsPB0yqnVhmRJvO5zpAArQLF3x2NaOpAplaMrePjolcY5yw2DiFZSS+KNdMHlf5EpQy1+BSCcwHdHUqpUd0CdKGo+A5zt4JrCM9IpgNJeVqpcec23fYd3o=
    client_secret: AgA5cvQX8x5yzuNGPHVnUcJMvXrb+TqG8UU7vwpOvkRfv375Afk/b+XV+e+uNJncRXaXeeems0YomNxSlsPTgE5InDvVgb0hncyA4JM4l+N7+rE3wr1mmMkRegbxxWco5T+n+OqL87HBGzR4wzFiq0WidE9YKaip4SZtatGEnqPn7oc5AbBFKzBzB288SifqrbinQJ5C/cT30vBtVwSzqixFgyBB0A0VsgeHyo64m+NuyOZHWCCMAFTg35MglT3bGWXjPVTAqUR4pK+2ybQaKxNnrgShQE9wiv0MDrLZXE2zt1GZvtNWIETijBaBHiFTRXy3YyxRMZZWT9pcA3tpIYGQ5WvNmZ0FDVcujUlLGZTx5MWwQrav+dP+pcVR+9MOUZzsW20psCC4r4Jhn2DTv0Z3xUCo3+q71O1UBeNzsopLEvXDlzOwn1y+8zQqivc0XZ4Gq7IE9mPoEJu5w2yf62MqVXk3jQ7cIpfx82dzGhVkSEAgMVrkmpABZZTdUd1R3hB47X0+5VQsXnYn9Zvmmy/fE/6Mk22ZCr/GO6Lpu5AlwC6X8CbPMx3cg6P6SkmBO6wUo4Xu/McmyA4zKHq8yq1uQaBAITvxXNAkv7cxB7YWDC/Ekuj7FbnXwMANlzNuRSC224BbCwg9OmWhYrvOQUMTJBKY07o2CPQW8t8P4TUt748/l3m7nSdS/TESv0DPJE99Dw86iBjx+0VKqHKjAqlIO+rHBKdx1arJ8YAOtXzMW2zFmzHHbM35nJD3g+gcDjVQRbnDbPbwF04n3Q==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
