---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCWOyqjvm342qVEDLZ3rjVYcwNu6M6OsWGFtPbbB8jz3+h9xmaffvggF9yRN6IDBzDh4cLCWqJN/kPGZt41itZCGCCTKjX8xSzEfrN01SJeargdusTAOReOBe/GivM+OWcr8k091fLFtldgyAkmnjfgtJ3TgtwH99ANFj733Pzn62XKavaDWWXBgnIiUCslZQKZmhsWepPIGSShea+4dBfrTBQTjKw3FijaL4oJMxiRpNy7zve4j/I5wohZ6pSxnAVnzaE8Bj4/aZOtNdoqno66recwq3AjkE72dTARM/ecsI7Zo2lLxjPQkw/ydzD1HE3gsgjrTCDgyyJeFpwVGl/Q0U6dqBMnEuWKyacJ2XMKcORfL6CI+qjBpWY3D+atwYPpNTIPKRAwmRibuN7b+sTJ/vu6WzYUUd/b1rT9B5nStBBFyVOsqzGUnGZYJhtEdZqtUpl9SCFqBUiWTiBnKj3b3jYCvV+vDQsKNiOVl9d9w5Q5JozDKChypze83ZN4mjnLOIHLCBRXbZZs1e+ZjsbJPEPxNSbsnSkTMwlMBUC/XtIs81jVKZq/jRKWLHFHWVan8z6pzIq/mAoTZBfk8RXlbllWvXVleRankVDd7W++2ktIhR6cEZWb1RSvtDfwryzkRCeUAVmi2jANvYvKne7gT+PkRsox6qf4DdYcKxx536jivu2HwAAiaNw+oA0nUVlN2z0dv41tDtjoE6M=
    client_secret: AgCYlYSZppFRNwZlUn3ucgXdmaqm5MQYcWsBFk4WRGXHDikJPze3b4rXZW6QRRgHf8OYmY+uvjS3/YcLaIt1SQbBeJDYTQhf3bF2Ps2c4mdxKzdJnsDtj3DVSXlJcRPYafoVomExQS1kGZq6i4C+DH5e7O0Gc+tkflwDhM3Clo69V52q88nAAlTjZXP+uKAwOlxV81dPlLovVyBs0BxvZf1kmWb7zWy5eVN8wzV0jHvNMbFEk/H6cOWBS2CTSaM/zyf/h335mlWw2xwmhKy5X/NDJcsrS0yU/eoZ6cCieLviHiCaRhgkJYbM7ucjKCqt+27OW43rDXOSVtNhAq9zzUflDGGj0/+5AJqItKEOvMrsQqRm9rxjrzDPb0xM/jqG21s1NgCcrZQVYMfERR66OlNeEB3yxoH0U6sKLcnFety3YKTb+gAtoRhT8zJcz+rxn9Ecic3A79wlQyc5T3TR0i0Zt9kQVspdMq9es3Ae/t2hPQm9Zh+uP8HLfVjJSdoBeNIgoAV4E0LUOnXy3KrwIb+KhCyyIIkJ9LrxhwNlbhzTyKZheoZAphzGkLEF80ggEaAO6goljM81BbPmYofwvNWwlrZSPtc1jl832MedRhiTQ0hj3b1ubog+izfl0MzaNlpQMwjlaHGgGKNQvhA1rJLGk+5zJ8VTsjuGRJ3SRuUUt0TYtRUIsAUiQHgazTHwGMax29xQgRU+hrqJKme9FF+HJVbHNYTyQmxVlj0PNK93MSzHryBdQIzpC100quR87ptEgJr1sXVThCeoZw==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
