---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBCkvxHi+m9D9WY2IZTerqOGgRfOjY0R1p6CH5Va6DHpbX07dJFG6cpvr44xfs3RoSjwRAkdb/Vb60NTnRgIoVVgtqvsVxHHm2nafzfknFOXuYUhU/y2VX/pPFGDvdowIfHjUnP1N2FFY95bNHunBu0l1zt9cx5mcqbJy+AUGYIYmKvTRhOwRwVAA5CvcKcuq1ikdhjH29qjT7QnZUKanMfNWpEN0eRFfNW3CVP403jmanFKE6waSEi7DJbHb7itS8B5TlHfGNl0m1czwZjKyYLm08qFBbwkwPLI6M0//QQIrZydguBti+OWEYHy76LZ9Muj9xFUzic3PcXxZmLT3xAulJU1MiRy1Ufv4EVMDTbssVNxE3H9Fv2fVeFuxwT9SlBEXSeaM6IDEf/DgEbBW+1OAqNMo9yhEHtWj//2EO+j9lReLULrXgkMpT6dSuwpFuTkos2KQHLc/mUhwEA/Y+yeGS9Ib6y94Rast0XGxeueMbAd/GNbfHyoKi3DAhux71jrkEk2pwWzcJCvapvedDbakHMPV1WPjM8QGXZK/z+Cm78WmIwpM8BEQ2oEAIiHR5MzethsZ7fsm6DMhC1Uangxt97S5t31Mvw3Y6TTJJCTvFZVpglk63cDG+qh4qR/Bn9QP+RvfV6E9w9CmiFWyT0qR+nndq/O+Wuh79CEX5CYYoG7yGM4QcQKDaCa1K9c1ahfAk4OjZpUk+psTg=
    client_secret: AgB4bdEDhTr+iM0QBloVWWUPMsx/Z7HPX9Y18zZUpGrgmL8wuZ6Zon24PgaaEvPl/KELg1GPxz/ZK0mCjwlaI/sQpf1Vjd0MBfODJu6qTx3938b0OM4jd73aEDdt1PfSbKtTyu2JqMLwXX9TYopH5RNpgoGpv3CQ4xLa/nLqQXkcXjCSE40NnYSdqD5R4Ucr/GDADCmXiPgLO2UZdj3cGt68kjqcGYIOg+nPp1Wnw+i7A7rKDVZcpPf4Pnd5MTVdEJMG2pvclPHS1TF4ji18Ffb86DmDIepzXnguLYfzKku2NjbYGJ9yPbPScbAn77wh+DA4smbF+oKd4XnCzfcbAhkrLSjORvNXeM9qbo1tr+1szhm2UXTLURf49f5tq433ma/uFmN00Yzou7bnCzzeFsNFgZUIwPS/u35JYiDCE3UZSti4NTbNJ0NyTPxVs4WJLzPPNfJUZyLTsw7meomriKdsGSbuTr+HLzicp1gsUo9ExhUlQkz6wwClRxWs9MZm2ixBIAYG81PzK80NmTTr2CDb3eKwKOaIhIURg/5eBW7kEK+/jim86jEHTjxEY/1PRkKzKbHkg8W/ZRGtoZHQiaG13hh2v4QomTjRXqFk9tTKiswme0buyQZ6GJ+8N31VwiI3sTCaC6NIo1HfBrJut53/EwNZJUgYL/DCMDb8vih+WyI1cyI2FtH1QgdDF2HDAFRE+55UirtGFWl13WzM3nBzrpVxVcCIeTmjeUxFxxV/DbkncHHMadM0W46DHiJbbr+TVzqSCScmRz/Mhw==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
