---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgB5zNfdMrV6VEPHuVNSbBVlbzT9D+BWT2oI/577yHTfLzP6gcCvgc9z2MWT77Tj9SvCnUuwnVXrn2KBkiZAQesZh9KgzUxRh8J54Jm2UP6zEI5+d1bD0HYMA6cbV63oN9wKwsACUz6voObcvR5r4fIzLmSR6cYEfl+cIUN4TTpRuB233HXk3xucwoXioL15rlu0oOV/08G/E5RYOmvYPEXgNF5RM9RLGsPigpS7p2O1j4fw4FuMpOF+vDFo1OsV7MewQy6G0RZlmrSu5n0Lz4e35B/PWONx/n+Ha1EbJYkcUq01UDccFChNrLvxLWgj2wg30Fa24uFnJxFbkbgWpiyivaToelQ9mMnVSN2XS4uZuKvdCyWjtleSMGA78NhmUVXxLIVT4wh/kWYkzIrCM9VV8MhSEFPKWYTgn8fBnvvWoKIfZdDrxA4MuE7t6sb+ypSAFn41ghC4jZq8QeKVjJBlfA3uDH33ezFO3/Mncs0N6KGMs25875i20F+OlNnfgRWA4AwJl523RwHJ1eiMW84546kQ4OJUou9n+9dFt4m7dGAAeS6EgWk8mLq9+x3DkWOaH7t+NYo7HwLb/fo0ws6e8ZTSIPMFamkXPTysrm1WeqbDBJxzslXvuiV6PFBhKeA8jfGQQ3B/KAwfRBdG1aLtXBOp22xNPiqHdvAZSubvLLQclElv7RtlTIXJ8qIgX5Ma0Xw+GPcCnfo3qhI=
    clientSecret: AgACrD7GbzsfHh0mFNFCCPnBAWmjvj3Pqfq6Iu1VROWVSbzvGQVw2/UnZ1IDa5BW+DxN2HqW/ghIa1lXFhElvp0VopOQ+5TuFevjb3RYbt6BP4XD+gdZkv85ctBAUuUDRP1AjGiUDT/PKjcGoTUQg5dh67B/xW87mKAe6qG6hSDyAYTVSBujaDOm+7oqNrBphFoqzrbAMbb2COV9Y7mMybyp7xm6q9ybzd+CTlBfcnAcH9fQgpVGLJUCYp2uiC+FlgmeAL5GAujU9G7Q4HnnD0J+5oaFAKs0c2N8BsxP8u6uDzapDH4FEm4h92JSOvpCsWo8fou5pDgH5VO9Ca0fEfruxyUOnopZ+De5As6POyKwoXQ+8ZM4vj8mBcAY7r6huGSRz3F4cYgmos6obmWJVsxo9oK/WjeN8DBOzEc9CmN20oFHEIsL9AM6+r4zYtSvj+bo4FUKO7rsWjq7DUOSpmap8v+LluH0nwbwK+E2N0bapW4HxJKOfdUDJZbI3NPdfRjqR72SfNN/Y/fsUvZto+b3mKwDCbhcBHz00uguZg4z1RT4XOcQ/iXbU1JoLYklj56sCcayWGl3vTh5AiaOYwXFYwYJhNJxi0rUgUM6lR+6MyWPMZf94o//nYkgZrPB68TaerP47+M+AyiN2RdAJtfNpLwbVTmbMhxUzW0puIpysjtM4DhWQX4beNKOoS8c42NkUyJ0jBEdJzf4kWF7EJ7sgMpjGFLARuV58hFDhXzror9P3GbzN8jVUD6OfFZlGhUMsn5vtD7OA/1hiQ==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
