---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCR27TvbrfRlexgRjONDy5wlMhCWnloocIhEx4fem2lI6Timmdn0N4qKMP0wSlJsELjgTat+04L5Ooi0mfHTcC8HRXEWGABKKqy4UpzEB43bznGHwbg1yyb/TW46N5vipmBGScQZ71jseLExjDsvP/k+KkVCUw6GI7Yu4N/cuqYeNDvr9blUnfUJ3/dACpD3W3sqJu6ciVvpwQeFs+JfpogIWhrvY/hRlQupkte/TLsDP5h5KiSaspHmSvG9iGjcPap5kkNKkMh6bxy8VO+0jU8W7OA78TJ1kNnRiTqIWxXE+hKU3M6UgEwkmK6hRg5j1bsOpQtVN3uBDEb1DdKhCgRnwAuHRsWlOlxn072MpQhYFQxtBBvGMWO/R/KKYkraY1w4X/D6ZVFW6NY47jpOKpWpzKhKk4jlVd2uov/9qZMzD5KOIA8tKQacQsfwkFEGkcM0h/MbUwN1VLBk+2OJfoy/9tYDaUg+u0nFXWb8Z12iJeQj3pC6phdA4N4qp36vSSQkaQXBVyJSm8TBhSXhYj2gjxTtYXhnB/YzQ/17kyfR012So83cYU1PW1WUwKa67yLbSYnLuEF+x6iWVkFKtl6Gajt0TT9QbGweyf4OKgpaOLRRNHxkfoIMes1JTszbOhRIYPtyveAUWFPu7IvrB824+LXIZc2f/lyDaz1nP+fEkW4fdLbLNvBbrgLeQ4ZTHWn3bmF44usdIiSZ4E=
    client_secret: AgCI5Qw/7NmVW8+qy1iZDJwMiPCYLEXUpnFiIcUS79yquYpRqG5ULKGhsiFtONPNNWwh0rYz1Di+SG3elixoUgnTpGwPSazFu6MPFlDVRQDNXLtMTjX1FLnA0/xVLjGMpIJaRNVFlSOpHTvXC4XXuHwQ8uFwz3hPa0hH11qwPWhgZeHGoLODef0g2XEgZf1S9BKqHWNppypPocvmlQf/xucK0UtqZDmDQdf8+Xudnv/gYzRxRVFl927knTQwBQZHMBMqv0kJP20HnlsbdHhpZ6P94TXjhLihrdbFF77s4Z+61Vg5m3VP8eA5tYvDa5p3H7hxrm6a218H32pqxqRoNd77zblAqQW/7Swjrp7E1JDnTrZbZbN9WAUeNuMHzqOk8fQPrF2U/XXZbSgu8A6MWG6TJ7HuVgkdJ2ipE6HvbV2CE0T4oVij4jRuUdtyXVAqooGWg2B35md3Katjzil6cEsNAxzUoK8lDtujH69C/cXHGVa4eRT/zQoLHrStSEbYLJvysG+qWD/babsSClAMznQQz7vBuFSwoE7jQ7J5XPLCWWKxmx9BroCk1Dd0R/YPyctzlouaglspJQf4qQ8SLkOk1sx5dRUpn1dxQJKh2WxI1I7ofVhQ7YzR7ThnmiYBe0rYAi+cCYGs64XNkR2kA5k2evc03/hWRnRAFD4+CYv2f0xEQKxMKhMWWBi/X8CDWzEcEjj37A35qTrFx3tltz0r1/l+5oD1EbXs0YoJXtEN40JnMMqmPCc8imXk7iw01saejQ9F6+zVSq4v7g==
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
