apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: "https://charts.bitnami.com/bitnami"
      chart: "keycloak"
      targetRevision: "21.0.1"
      helm:
        values: |
          production: true
          proxy: "edge"
          postgresql:
            enabled: false
          externalDatabase:
            existingSecret: "postgres-pguser-keycloak"
            existingSecretHostKey: "host"
            existingSecretPortKey: "port"
            existingSecretUserKey: "user"
            existingSecretDatabaseKey: "dbname"
            existingSecretPasswordKey: "password"
          initContainers: |
            - name: realm-ext-provider
              image: curlimages/curl
              imagePullPolicy: IfNotPresent
              command:
                - sh
              args:
                - -c
                - |
                  curl -L -f -S -o /extensions/home-keycloak-theme.jar https://github.com/MaikBuse/home-keycloak-theme/releases/download/1.0.0/home-keycloak-theme-1.0.0.jar
              volumeMounts:
                - name: extensions
                  mountPath: /extensions
          extraVolumeMounts: |
            - name: extensions
              mountPath: /opt/bitnami/keycloak/providers
          extraVolumes: |
            - name: extensions
              emptyDir: {}
          ingress:
            enabled: true
            hostname: "keycloak.maikbuse.com"
            path: "/"
            ingressClassName: "traefik"
            tls: true
            annotations: {
              cert-manager.io/cluster-issuer: "common-cluster-issuer"
            }
          adminIngress:
            enabled: true
            hostname: "keycloak-admin.maikbuse.com"
            path: "/"
            ingressClassName: "traefik"
            tls: true
            annotations: {
              cert-manager.io/cluster-issuer: "common-cluster-issuer"
            }
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
