apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: "https://charts.bitnami.com/bitnami"
      chart: "keycloak"
      targetRevision: "21.0.1"
      helm:
        values: |
          production: true
          proxy: "edge"
          postgresql:
            enabled: false
          externalDatabase:
            existingSecret: "postgres-pguser-keycloak"
            existingSecretHostKey: "host"
            existingSecretPortKey: "port"
            existingSecretUserKey: "user"
            existingSecretDatabaseKey: "dbname"
            existingSecretPasswordKey: "password"
          ingress:
            enabled: true
            hostname: "keycloak.maikbuse.com"
            path: "/"
            ingressClassName: "traefik"
            tls: true
            annotations: {
              cert-manager.io/cluster-issuer: "common-prod-cluster-issuer"
            }
            extraHosts:
              - name: "keycloak.vectory.app"
                path: "/"
              - name: "keycloak.vectory.dev"
                path: "/"
            extraTls:
              - hosts:
                  - keycloak.vectory.app
                  - keycloak.vectory.dev
                secretName: keycloak.vectory-tls
          adminIngress:
            enabled: true
            hostname: "keycloak-admin.maikbuse.com"
            path: "/"
            ingressClassName: "traefik"
            tls: true
            annotations: {
              cert-manager.io/cluster-issuer: "common-prod-cluster-issuer"
            }
            extraHosts:
              - name: "keycloak-admin.vectory.app"
                path: "/"
              - name: "keycloak-admin.vectory.dev"
                path: "/"
            extraTls:
              - hosts:
                  - keycloak-admin.vectory.app
                  - keycloak-admin.vectory.dev
                secretName: keycloak-admin.vectory-tls
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
