apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: "prometheus"
      targetRevision: "25.20.1"
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: "grafana"
      targetRevision: "7.3.9"
    - repoURL: 'https://github.com/MaikBuse/cloud-config'
      targetRevision: 'main'
      path: 'helm/monitoring'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: "monitoring"
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
