apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vectory
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Project for the Vectory Application"
  sourceRepos:
  - '*'
  destinations:
  - namespace: vectory
    server: https://kubernetes.default.svc
