apiVersion: apps/v1
kind: Deployment
metadata:
  name: "home-web"
  namespace: "home"
  labels:
    app: "home-web"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "home-web"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "home-web"
    spec:
      imagePullSecrets:
        - name: "image-pull-secret"
      containers:
        - name: "home-web"
          image: {{ .Values.web.container.image | quote }}
          ports:
            - name: "next"
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: "/"
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "475m"
            limits:
              memory: "1024Mi"
