apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
 name: loki-cluster-output
spec:
 loki:
   url: http://monitoring-loki-gateway.monitoring:80/loki/api/v1/push
   configure_kubernetes_labels: true
   buffer:
     timekey: 1m
     timekey_wait: 30s
     timekey_use_utc: true
