apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: loki-cluster-flow
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: json
  match:
    - select:
        labels:
          app: "vectory-backend"
  globalOutputRefs:
    - loki-cluster-output
