apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
    - url: http://monitoring-loki-gateway.monitoring:80/loki/api/v1/push
      tenant_id: tenant-1

    positions:
      filename: /tmp/positions.yaml

    target_config:
      sync_period: 10s

    scrape_configs:
    - job_name: systemd-journal
      journal:
        path: /var/log/journal
        max_age: 12h
        labels:
          job: systemd-journal

      pipeline_stages:
      - json:
          expressions:
            severity: PRIORITY
            message: MESSAGE

      relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'
      - source_labels: ['__journal__transport']
        target_label: 'transport'
      - source_labels: ['severity']
        target_label: 'severity'
      - source_labels: ['message']
        target_label: 'message'
      - action: labelmap
        regex: '__journal__(.*)'
