apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: "common-cluster-issuer"
 namespace: "cert"
spec:
 acme:
   email: "contact@maikbuse.com"
   server: "https://acme-staging-v02.api.letsencrypt.org/directory"
   privateKeySecretRef:
     name: "tls-privatekey-secret"
   solvers:
     - http01:
         ingress:
           class: "traefik"
